# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          registry-url: https://registry.npmjs.org/
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#      # 获取当前包的版本号
#      - name: Get Package Version
#        id: get_version
#        run: echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
#
#
#      # 发布成功后发送钉钉消息
#      - name: dingtalk robot message
#        uses: fifsky/dingtalk-action@master
#        with:
#          url: ${{ secrets.DINGTALK_WEBHOOK_URL}}
#          type: markdown
#          content: |
#            ## kd-monitor 发布通知
#            > from github action message
#            kd-monitor ${PACKAGE_VERSION} 已发布! <br/>
#            稍后查看详情：[Npm 详情](https://www.npmjs.com/package/kd-monitor) [Github 详情](https://github.com/yun8711/fe-monitor) [Gitlab 详情](http://gitlab.keendata.net/fe-extension/fe-monitor)"
